language: java
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
script:
  mvn test -B
